# ==============================================================
#                 DRAKESCRATES SETTINGS
# ==============================================================

roulette:
  # Tiempo en ticks entre cada paso de la ruleta (2-5 recomendado).
  tick-speed: 2

  # Cantidad total de pasos de giro antes de frenar en el premio ganador.
  total-steps: 45

# Separación de modalidades y Restricciones Vainilla
modalities:
  # Mundos donde el juego es 100% Vainilla. En estos mundos cualquier
  # crate o recompensa con Slimefun queda ESTRICTAMENTE bloqueada.
  clasico-worlds:
    - clasico
    - clasico_nether
    - clasico_the_end

  # Mundos tecnológicos con Slimefun activo y permitido.
  slimefun-worlds:
    - bskyblock_world
    - bskyblock_world_nether
    - bskyblock_world_the_end
    - oneblock
    - survival_sf

virtual-crates:
  # Permitir abrir crates mediante el menú virtual /crates
  enabled: true
  # Si el jugador tiene llaves físicas en inventario, se consumen primero antes de las virtuales
  prefer-physical-keys: true
