package me.jackstar.drakescrates.oracle;

import java.io.File; import java.sql.*; import java.util.*;

/** SQLite persistence. A draw debits its key, stores its claim, and updates pity in one transaction. */
public final class OracleRepository {
    private final String url;
    public OracleRepository(File file) { url = "jdbc:sqlite:" + file.getAbsolutePath(); try (Connection c = connect(); Statement s = c.createStatement()) { s.executeUpdate("CREATE TABLE IF NOT EXISTS drakes_oracle_keys (uuid TEXT NOT NULL,relicary_id TEXT NOT NULL,balance INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(uuid,relicary_id))"); s.executeUpdate("CREATE TABLE IF NOT EXISTS drakes_oracle_pity (uuid TEXT NOT NULL,relicary_id TEXT NOT NULL,fail_streak INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(uuid,relicary_id))"); s.executeUpdate("CREATE TABLE IF NOT EXISTS drakes_oracle_pending_claims (id INTEGER PRIMARY KEY AUTOINCREMENT,uuid TEXT NOT NULL,relicary_id TEXT NOT NULL,reward_id TEXT NOT NULL,commands TEXT NOT NULL,claimed_at TEXT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP)"); } catch (SQLException e) { throw new IllegalStateException("Could not initialize oracle database", e); } }
    private Connection connect() throws SQLException { return DriverManager.getConnection(url); }
    public int balance(UUID id, String relicary) { return value("SELECT balance FROM drakes_oracle_keys WHERE uuid=? AND relicary_id=?", id, relicary); }
    public int pity(UUID id, String relicary) { return value("SELECT fail_streak FROM drakes_oracle_pity WHERE uuid=? AND relicary_id=?", id, relicary); }
    private int value(String sql, UUID id, String relicary) { try (Connection c=connect(); PreparedStatement p=c.prepareStatement(sql)) { p.setString(1,id.toString());p.setString(2,relicary);ResultSet r=p.executeQuery();return r.next()?r.getInt(1):0;} catch(SQLException e){throw new IllegalStateException(e);} }
    public void addKeys(UUID id,String relicary,int amount) { if(amount<=0) throw new IllegalArgumentException("amount must be positive"); changeKeys(id,relicary,amount); }
    public boolean takeKeys(UUID id,String relicary,int amount) { if(amount<=0) return false; try(Connection c=connect();PreparedStatement p=c.prepareStatement("UPDATE drakes_oracle_keys SET balance=balance-? WHERE uuid=? AND relicary_id=? AND balance>=?")){p.setInt(1,amount);p.setString(2,id.toString());p.setString(3,relicary);p.setInt(4,amount);return p.executeUpdate()==1;}catch(SQLException e){throw new IllegalStateException(e);} }
    private void changeKeys(UUID id,String relicary,int amount) { try(Connection c=connect();PreparedStatement p=c.prepareStatement("INSERT INTO drakes_oracle_keys(uuid,relicary_id,balance) VALUES(?,?,?) ON CONFLICT(uuid,relicary_id) DO UPDATE SET balance=balance+excluded.balance")){p.setString(1,id.toString());p.setString(2,relicary);p.setInt(3,amount);p.executeUpdate();}catch(SQLException e){throw new IllegalStateException(e);} }
    public void setPity(UUID id,String relicary,int amount) { try(Connection c=connect();PreparedStatement p=c.prepareStatement("INSERT INTO drakes_oracle_pity(uuid,relicary_id,fail_streak) VALUES(?,?,?) ON CONFLICT(uuid,relicary_id) DO UPDATE SET fail_streak=excluded.fail_streak")){p.setString(1,id.toString());p.setString(2,relicary);p.setInt(3,Math.max(0,amount));p.executeUpdate();}catch(SQLException e){throw new IllegalStateException(e);} }
    public record Draw(long claimId, OracleReward reward, int pity) { }
    public Draw draw(UUID id, Relicary relicary, Random random) { try(Connection c=connect()){c.setAutoCommit(false);try { int keys=query(c,"SELECT balance FROM drakes_oracle_keys WHERE uuid=? AND relicary_id=?",id,relicary.id()); if(keys<1){c.rollback();return null;} int streak=query(c,"SELECT fail_streak FROM drakes_oracle_pity WHERE uuid=? AND relicary_id=?",id,relicary.id()); OracleReward reward=pick(relicary.rewards(),streak,random); try(PreparedStatement p=c.prepareStatement("UPDATE drakes_oracle_keys SET balance=balance-1 WHERE uuid=? AND relicary_id=?")){p.setString(1,id.toString());p.setString(2,relicary.id());p.executeUpdate();} int next=reward.isTopTier()?0:streak+1; setPity(c,id,relicary.id(),next); long claim;try(PreparedStatement p=c.prepareStatement("INSERT INTO drakes_oracle_pending_claims(uuid,relicary_id,reward_id,commands) VALUES(?,?,?,?)",Statement.RETURN_GENERATED_KEYS)){p.setString(1,id.toString());p.setString(2,relicary.id());p.setString(3,reward.id());p.setString(4,String.join("\u001f",reward.commands()));p.executeUpdate();ResultSet k=p.getGeneratedKeys();k.next();claim=k.getLong(1);} c.commit();return new Draw(claim,reward,next);}catch(Exception e){c.rollback();throw e;}}catch(SQLException e){throw new IllegalStateException(e);} }
    private int query(Connection c,String sql,UUID id,String relicary)throws SQLException{try(PreparedStatement p=c.prepareStatement(sql)){p.setString(1,id.toString());p.setString(2,relicary);ResultSet r=p.executeQuery();return r.next()?r.getInt(1):0;}}
    private void setPity(Connection c,UUID id,String relicary,int n)throws SQLException{try(PreparedStatement p=c.prepareStatement("INSERT INTO drakes_oracle_pity(uuid,relicary_id,fail_streak) VALUES(?,?,?) ON CONFLICT(uuid,relicary_id) DO UPDATE SET fail_streak=excluded.fail_streak")){p.setString(1,id.toString());p.setString(2,relicary);p.setInt(3,n);p.executeUpdate();}}
    private OracleReward pick(List<OracleReward> all,int streak,Random r){List<OracleReward> pool=streak>=40?all.stream().filter(OracleReward::isTopTier).toList():all; if(pool.isEmpty()) throw new IllegalStateException("Relicary lacks a legendary/divine reward"); double bonus=streak*1.5, total=0;for(OracleReward x:pool)total+=x.weight()+(x.isTopTier()?bonus:0);double roll=r.nextDouble()*total;for(OracleReward x:pool){roll-=x.weight()+(x.isTopTier()?bonus:0);if(roll<=0)return x;}return pool.getLast();}
    public List<String> claim(UUID id,long claim) { try(Connection c=connect();PreparedStatement q=c.prepareStatement("SELECT commands FROM drakes_oracle_pending_claims WHERE id=? AND uuid=? AND claimed_at IS NULL")){q.setLong(1,claim);q.setString(2,id.toString());ResultSet r=q.executeQuery();if(!r.next())return List.of();String raw=r.getString(1);try(PreparedStatement u=c.prepareStatement("UPDATE drakes_oracle_pending_claims SET claimed_at=CURRENT_TIMESTAMP WHERE id=?")){u.setLong(1,claim);u.executeUpdate();}return raw.isEmpty()?List.of():List.of(raw.split("\u001f",-1));}catch(SQLException e){throw new IllegalStateException(e);} }
}
