package me.jackstar.drakescrates.oracle;

import me.jackstar.drakescraft.utils.ItemBuilder; import me.jackstar.drakescraft.utils.MessageUtils;
import org.bukkit.*; import org.bukkit.entity.Player; import org.bukkit.event.*; import org.bukkit.event.inventory.*; import org.bukkit.inventory.*; import org.bukkit.plugin.java.JavaPlugin;
import java.util.*;

public final class OracleGuiService implements Listener {
 private final JavaPlugin plugin; private final OracleService service; private final OracleYamlRepository relicaries;
 public OracleGuiService(JavaPlugin plugin,OracleService service,OracleYamlRepository relicaries){this.plugin=plugin;this.service=service;this.relicaries=relicaries;}
 public void open(Player p){Inventory i=Bukkit.createInventory(new Holder(),54,MessageUtils.parse("<dark_blue><b>El Oráculo de Delfos</b></dark_blue>")); ItemStack frame=new ItemBuilder(Material.BLUE_STAINED_GLASS_PANE).name("<dark_blue>✦</dark_blue>").build();for(int s=0;s<54;s++)i.setItem(s,frame);int[] slots={11,13,15,29,33};int n=0;for(Relicary r:relicaries.all()){if(n>=slots.length)break;int keys=service.balance(p.getUniqueId(),r.id()),pity=service.pity(p.getUniqueId(),r.id());i.setItem(slots[n++],new ItemBuilder(r.material()).name("<gold><b>"+r.name()+"</b></gold>").lore("<gray>Ofrenda: <yellow>"+r.keyName(),"<gray>Llaves virtuales: <aqua>"+keys,"<gray>Gracia Divina: <light_purple>"+pity+"/40","","<green>Click izquierdo: 1 invocación","<green>Shift + click: hasta 10","<yellow>Click derecho: ver recompensas").glowing().build());}p.openInventory(i);}
 @EventHandler public void click(InventoryClickEvent e){if(!(e.getWhoClicked() instanceof Player p)||!(e.getView().getTopInventory().getHolder() instanceof Holder)){return;}e.setCancelled(true);if(e.getRawSlot()<0||e.getRawSlot()>=54)return;Relicary r=relicaryAt(e.getRawSlot());if(r==null)return;if(e.isRightClick()){preview(p,r);return;}int count=e.isShiftClick()?10:1;int opened=0;for(int x=0;x<count;x++){OracleRepository.Draw draw=service.open(p.getUniqueId(),r.id());if(draw==null)break;opened++;animate(p,r,draw,x*8L);}if(opened==0)MessageUtils.send(p,"<red>No tienes " + r.keyName()+".</red>");else p.closeInventory();}
 private Relicary relicaryAt(int s){int[] slots={11,13,15,29,33};int i=0;for(Relicary r:relicaries.all()){if(i>=slots.length)return null;if(slots[i++]==s)return r;}return null;}
 private void preview(Player p,Relicary r){Inventory i=Bukkit.createInventory(new Holder(),54,MessageUtils.parse("<gold>Vaticinio: "+r.name()));int s=0;for(OracleReward reward:r.rewards()){i.setItem(s++,new ItemBuilder(reward.material()).name("<gold>"+reward.name()).lore("<gray>Rareza: <yellow>"+reward.rarity(),"<gray>Peso: "+reward.weight()).build());}p.openInventory(i);}
 private void animate(Player p,Relicary r,OracleRepository.Draw d,long delay){Bukkit.getScheduler().runTaskLater(plugin,()->{if(!p.isOnline())return; p.playSound(p.getLocation(),Sound.ENTITY_LIGHTNING_BOLT_THUNDER,.45f,1.4f);service.deliver(p,d.claimId());MessageUtils.send(p,"<gold>✦ <yellow>El Oráculo te concede <white>"+d.reward().name()+" <gray>("+d.reward().rarity()+")");if(d.reward().isTopTier())Bukkit.broadcast(MessageUtils.parse("<light_purple>✦ [El Oráculo] <gold>"+p.getName()+" ha recibido "+d.reward().name()+" ✦"));},40L+delay);}
 private static final class Holder implements InventoryHolder{public Inventory getInventory(){return null;}}
}
